name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          #username: ${{ github.repository_owner }}
          #password: ${{ secrets.CR_PAT }} # - must be in GitHub Secrets!
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/matkonnerth/opcuatesttool:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
