name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  integrationTest:
    runs-on: ubuntu-latest
    services:
          testContainer:
            image: ghcr.io/matkonnerth/opcuatesttool:latest
    steps:
    - uses: actions/checkout@v2
    - name: run test script
      shell: bash
      run: ./api/tests/rest/BasicTest.sh
